name: Display Top Repositories

on:
  schedule:
    - cron: '0 0 * * *' # Menjalankan setiap hari pada pukul 00:00 UTC
  workflow_dispatch: # Memungkinkan menjalankan secara manual dari GitHub UI

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README.md with Top Repos
        uses: jaywcjlove/github-readme-magic@v1.6.0
        with:
          # Pastikan path ini benar jika kamu ingin menggunakan config file terpisah
          config_file: .github/workflows/readme-magic.json
          readme_file: README.md
          gh_token: ${{ secrets.GITHUB_TOKEN }} # Token otomatis GitHub untuk otentikasi

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: Update top repositories in README"
          # Pastikan branch default kamu (main atau master) sesuai
          branch: main
          push_options: "--force" # Gunakan ini jika ada masalah push, tapi hati-hati
